### ISSUE TITLE
SpotifyServiceBase.IsPlaying always returns false

### ISSUE THREAD

**Issue by timendez** [JoshLmao/Spotify4Unity#10]
Hi, I'm trying to detect when Spotify is playing, and at first glance this was just what I needed. However, it always seems to be returning `false`. Doesn't this need to be a function with a network request in order to get the proper state (e.g. if Spotify is playing on a different machine)?

Perhaps I just don't understand this enough, but by no means is this a dealbreaker, so don't worry if there's no functionality for it!

**Comment by JoshLmao** [comment]
Hmm, that IS a strange one. Can you try logging the output every frame and see if it's still false? Then, try changing the song to another one and see if it's still saying false?

**Comment by timendez** [comment]
Yep still false every frame. Tried changing/playing/pausing via the Spotify4Unity API and also the Spotify app on my phone, and also the Spotify app on my computer. The Unity app was running on my phone. I'm stumped!

**Comment by JoshLmao** [comment]
Okay, I think it must have been fixed in between your version and v1.4 (I'm on that now, developing). I thought it could be a Free vs Premium account thing but I tested it and it works 🤔 

I took the Android scene and added some text that shows the state and it's showing correctly. _(Excuse the broken Android screen)_
![](https://i.imgur.com/JuRYjVK.png)

I'm actually finished with v1.4 and adding iOS support so I'll finish up the documentation as fast as possible and get it out for you. By the way, which version are you using right now?

**Comment by timendez** [comment]
I'm on v1.3.1, also using a Premium account.

No rush on getting it out, this is a very low priority item for my application 😄

**Comment by JoshLmao** [comment]
v1.4 just got updated on the Asset store. Could you try updating and letting me know if you're still getting the same error?

FYI: "Android Spotify Service" has changed to "Mobile Spotify Service" so you will have to readd that script after updating

**Comment by timendez** [comment]
Unfortunately it's still false after the update

**Comment by JoshLmao** [comment]
Wow, okay. So a couple questions and things...

* What version of Unity are you using?
* What's your build target? Android/iOS/PC?
* Have you set your Scripting Runtime Version to .NET 4.x? (This is important in Unity 2018.2.x)
* When you update the asset, are you definitely overriding the old .dll's?
* Try calling SpotifyServiceBase.GetSongInfo(), and check **songInfo.IsPlaying**. Does that also show false? (This one makes an additional web request to Spotify on top of the update loop)
* Inside a script that inherits from SpotifyUIBase, override the OnPlayStatusChanged(PlayStatusChanged e) method. Is that functioning?

Apart from those, I'm struggling to see what could be causing it. Unless SpotifyServiceBase.UpdateInternal() method is throwing exceptions like **"Aborted SpotifyService internal update - {threadException}"** or **"SpotifyService internal Update loop exception - '{exception}'"** and you're not seeing them?

I know you say it's a low priority but if something's now working properly, I should get it fixed ASAP so I'm a little concerned 😬
