### ISSUE TITLE
SpotifyUIBase.OnTrackChanged is only getting called on startup

### ISSUE THREAD

**Issue by Eyliess** [JoshLmao/Spotify4Unity#12]
**Describe the bug**
SpotifyUIBase.OnTrackChanged is not being called when it's supposed to, only at startup - if I change the song, it does not get called. 
The same behaviour happens even on the Example Player Controller and with a full reimport of Spotify4Unity.

(This only started happening after I updated to the latest version of Spotify4Unity)

**Platform:**
PC

**Unity Version:**
2018.3.9f1

**Comment by JoshLmao** [comment]
Yep, I can confirm this is a bug in v1.4.1. I tidied up the internal loop system a little and missed that.

I've pushed an update to the store and it should be live in 24 hours. I'll update the release's section of the repository when it's live

**Comment by Eyliess** [comment]
Nice work!
Thanks for the quick response, my project, which is utilising the plugin, should be complete very soon in that case!

**Comment by JoshLmao** [comment]
No problem, quick responses is what I'm all about. Also, the update is live on the Asset Store now. (That was quick!) Give it a test and please close this if there aren't other problems

Good luck with your project! I'd love to see the final if you publicly release it 😉
