### ISSUE TITLE
Connect does not work after calling Disconnect 

### ISSUE THREAD

**Issue by Eyliess** [JoshLmao/Spotify4Unity#13]
Due to the way my Unity application is run, it will sometimes be completely frozen for unknown periods of time which seems to lead to the Spotify Service not being able to re-auth the user.

To combat this issue, I wanted to add a reconnect button - I called SpotifyService.Disconnect, and then SpotifyService.Connect a few seconds later (tried with up to 60). Once the connect method is called, the OnConnectionChanged method in SpotifyUIBase gets called with the result being that IsConnected is true.

Despite this, none of the SpotifyUIBase methods get called almost as if the service was not actually connected.

**Comment by JoshLmao** [comment]
Hey, massive apologies for the slow reply! I was on holiday all of last month so thank you for being patient 😊

I took a look and realized my issue and this should now work. I've added a Disconnect button to the ExamplePlayerController too. I'll release and update asap and close this when the update is live on the store

**Comment by Eyliess** [comment]
Thanks a lot!
Hope you enjoyed the vacation.
Once that update is ready I'll be able to release my application!

**Comment by JoshLmao** [comment]
That's good to hear! The update is live on the Asset Store now so update the package and you should be good to go. And I did, thank you 😊
