### ISSUE TITLE
Reference has errors 'Spotify4Unity

### ISSUE THREAD

**Issue by Marquant** [JoshLmao/Spotify4Unity#14]
**Describe the bug**
I get the following errors when importing your asset. 

```
Assembly 'Library/ScriptAssemblies/Assembly-CSharp.dll' will not be loaded due to errors:
Reference has errors 'Spotify4Unity'.

Assembly 'Library/ScriptAssemblies/Assembly-CSharp-Editor.dll' will not be loaded due to errors:
Reference has errors 'Spotify4Unity'.

Assembly 'Assets/Spotify4Unity/plugins/NET 4.6/Spotify4Unity.dll' will not be loaded due to errors:
Unable to resolve reference 'UnityEngine.UI'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
```

Can't seem to come around this problem. I was trying to follow your setup instructions though selecting "Scripting runtime version" doesn't seem to be available anymore in my Unity version. At the same time from what I have been able to find it should already be implementing .NET 4.6. 

Also been getting error for your slider scripts regarding the "override" parameter since the scripts can't find any methods to override. Simply removed override for now but still can't test anything because of this problem.

Tested against a clean Windows project. Tried re-importing severeal times etc. Nothing works. Managed to get it working for like 2 seconds without actually doing anything and haven't been able to re-produce that solution either.. Haha. 

Any ideas?

**Expected behavior**
Not getting any errors. 

**Platform:**
Android (tested against clean Windows project as well)

**Unity Version:**
2019.3

**Comment by Marquant** [comment]
From more googling I've been able to find out that UnityEngine.UI was moved into some package in one of the more recent versions. Could that be the culprit?

**Comment by JoshLmao** [comment]
Hey, apologies for the delay as I've been on holiday and just came back.

Yes, you're right. 2019.3 only came out a week ago and they have UI changes. Since it's in alpha, I'd like to wait until at least beta before trying to support that version though. I'll leave this open until I get around to it and if it's an easy fix, I'll update (and close this issue when done 😊)

**Comment by Marquant** [comment]
Alright, that explains it. I didn't really think about it beeing in alpha since I some time ago did a clean install of my PC and when I the other day installed Unity just decided to upgrade and use the latest version.

Will try an earlier version instead in the meantime. 😊
