### ISSUE TITLE
Funny bug with OnTrackChanged

### ISSUE THREAD

**Issue by Eyliess** [JoshLmao/Spotify4Unity#15]
**Describe the bug**
OnTrackChanged seems to only be called when the tracks name has changed.

**To Reproduce:**
Play a song, then play a different song but with the same name (Try Post Malone's Congratulations, and then Pewdiepie's one)

**Expected behavior**
The method gets called when the track changes.

**Platform:**
Windows

**Unity Version:**
2018.3.9f1

The issue isn't that serious so regardless, great work Josh!

**Comment by JoshLmao** [comment]
Thanks for finding this. I checked the code and it's pretty obviously a flaw. I'll update it asap

**Comment by Eyliess** [comment]
Awesome, snappy as always!
