### ISSUE TITLE
Can't Find Token from Token Saver

### ISSUE THREAD

**Issue by timendez** [JoshLmao/Spotify4Unity#16]
**Describe the bug**
I am trying to check for the refresh token existing in `PlayerPrefs` and am coming up empty trying to use `TokenSaver.PREFS_TOKEN_NAME`.

**To Reproduce:**
- Ensure the `Reuse Auth Token` option is checked in the Mobile Spotify Service script
- Connect to Spotify
- Close the app
- Reopen the app and try to log:
```
    Debug.Log(PlayerPrefs.HasKey("F:TokenSaver.PREFS_TOKEN_NAME"));
    Debug.Log(PlayerPrefs.GetString("F:TokenSaver.PREFS_TOKEN_NAME"));
    Debug.Log(PlayerPrefs.HasKey("TokenSaver.PREFS_TOKEN_NAME"));
    Debug.Log(PlayerPrefs.GetString("TokenSaver.PREFS_TOKEN_NAME"));
    Debug.Log(PlayerPrefs.HasKey("PREFS_TOKEN_NAME"));
    Debug.Log(PlayerPrefs.GetString("PREFS_TOKEN_NAME"));
```
- See that either `False` or an empty string logs.

**Expected behavior**
When I log `PlayerPrefs.HasKey("TokenSaver.PREFS_TOKEN_NAME")` I should see `True`.

**Platform:**
- Android

**Unity Version:**
- 2018.3.10f1 Personal

Just started back on this today, I'll respond back on the other issue I have open after I fix this one! :)

**Comment by JoshLmao** [comment]
You're doing this all wrong. You shouldn't and don't need to be checking PlayerPrefs for something contained in Spotify4Unity. If, for whatever reason, you want to check if Spotify4Unity has a previous auth token that it will try to use, you can do...

```
bool hasToken = TokenSaver.HasSavedTokenInfo()
```
...**however** this is all contained withing Spotify4Unity. So if you check the box to reuse auth, then the service will check for you if it can reuse the auth. If not, it will ask the user to give authorization again

**Comment by timendez** [comment]
Ah ok, thanks! Unfortunately it does seem to be logging `False` even with `Reuse Auth Token` ticked.

It can auto-log me in so I know the token is saved.

Any ideas here?

**Comment by JoshLmao** [comment]
Hmm, what version of the package are you on? Check the ReadMe.txt thats in the package folder. I may suggest updating to the newest

To correct your original way of doing it, **TokenSaver.PREFS_TOKEN_NAME** is a property in a class so you would need to do...
```
Debug.Log(PlayersPrefs.GetString(TokenSaver.PREFS_TOKEN_NAME));
```
...to find out if it exists. Make sure you have "Reuse Auth Token" ticked (otherwise it won't save any auth) and run it once to get authorization. Then on the next play, it will return true

I do just wanna say though **TokenSaver.HasSavedTokenInfo()** just does that code above

**Comment by timendez** [comment]
I'm running v1.4, I'll try to update to v1.4.5 and see if it changes anything. Thanks for the insights!

Logging `TokenSaver.PREFS_TOKEN_NAME` gives me `TokenJson` and logging `PlayerPrefs.GetString(TokenSaver.PREFS_TOKEN_NAME)` returns an empty string.

Going to try to update to v1.4.5 and report back!

**Comment by timendez** [comment]
Thanks @JoshLmao, the update worked 😄
