### ISSUE TITLE
GetDevicesAsync stalls

### ISSUE THREAD

**Issue by Xeethrax** [JoshLmao/Spotify4Unity#2]
Hello.

SpotifyService:989 stalls half the time and won't continue. Sometimes I have to enter/exit play mode 4-5 times before I finally get a response. Could be handled a bit better :)

BR

**Comment by JoshLmao** [comment]
Hey,

Is this in reference to the error "SpotifyService internal Update loop exception - (Exception)"? If so, sometimes the internal loop hits it's call limit and this is used to save it. I'm changing it to a LogWarning message next update so you can ignore it

However, from your title, if you mean the method GetDevicesAsync, that only exists in JohnnyCrazy's SpotifyWebAPI. I would say make sure you're on the latest release for that, however it seems to works fine and no one else is reporting that problem

**Comment by Xeethrax** [comment]
Quick response! Appreciated.

No, although I occasionally get that exception when exiting play mode, that has yet to be a concern. 

GetDevicesAsync is the problem. It blocks on the call and never times out. About half the time it never returns. It's somewhat weird - when it works, it usually keeps working. When it doesn't, I have to restart. Probably something related to the auth the first time around, but I haven't dug into it yet. I was kinda hoping I wouldn't have to ;)

**Comment by JoshLmao** [comment]
Okay, I understand your problem. So the method relies on being connected to the SpotifyWebAPI (obviously) however if it gets called without being connected, it hangs and does as you say.

You need to inherit the class from SpotifyUIBase (to get the callbacks) and then override the "OnConnectedChanged" which will be your starting point for using the functions. I've included an image below with the script I used to test it 😉

I'll try to get a fix for this problem and update it soon. Thanks for finding that

![Example Script](https://i.imgur.com/7SXXhuY.png)

**Comment by JoshLmao** [comment]
Wrong button 🤦‍♂️

**Comment by Xeethrax** [comment]
Cool, thanks. I'll give it a whirl :)
