### ISSUE TITLE
Edit scope pls. Birthday is removed.

### ISSUE THREAD

**Issue by ufodriverr** [JoshLmao/Spotify4Unity#21]
Link to all legal scopes:
https://developer.spotify.com/documentation/general/guides/scopes/#scopes

or let us choose scopes, this would be the best.

Cos current request gives Illegal scope cos of birthday.

**Comment by JoshLmao** [comment]
You can choose scopes, that was included in one of the lastest updates [(v1.4.7)](https://github.com/JoshLmao/Spotify4Unity/releases/tag/v1.4.7). That still being included is part of SpotifyAPI.NET and only recently got removed from the Web API, hence it being a problem. 

SpotifyAPI.NET should remove it soon however, just deselect it in the Advanced Settings of the Spotify Service
