### ISSUE TITLE
Repeat track isn't possible?

### ISSUE THREAD

**Issue by AskeDK** [JoshLmao/Spotify4Unity#25]
**Describe the bug**
When I try to to set Spotify to repeat on track, it repeats on playlist instead.

**To Reproduce:**
SpotifyService.SetRepeat(Spotify4Unity.Enums.Repeat.Track);

**Expected behavior**
I expected Spotify to be set to repeat on a single track.

**Platform:**
- Insert the platform you're targeting
I want to build for iOS and Android, but I have only tested for this bug in Unity Editor yet (with Spotify being active on same Windows device).

**Unity Version:**
- Insert the version of Unity you're currently working or the versions where you can create this bug
Unity 2019.2.5f1

**Comment by JoshLmao** [comment]
Hi,

Sorry for the delay. At the time, SpotifyAPI-NET didn't include setting repeat for all three modes, only the two. However, after adding support for v6.1.0 of SpotifyAPI-NET, you are able to set it to all three modes. Try the new v2.0 of Spotify4Unity which will allow you to do this
