### ISSUE TITLE
Query Audio Analysis

### ISSUE THREAD

**Issue by yusuken64** [JoshLmao/Spotify4Unity#28]
I would like to get the audio analysis for the purpose of making audio visualization.
Spotify endpoint:
https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis

I tried this but the analysis never has beats. 
```
var id = SpotifyService.CurrentTrack.TrackId;
var analysis = await SpotifyService.WebAPI.GetAudioAnalysisAsync(id);
```

**Comment by JoshLmao** [comment]
Hi,
Sorry for the delay. I've updated the package to v2.0 which provides full access to SpotifyAPI-NET. You will be able to access the GetAudioAnalysis from the updated Spotify client
