### ISSUE TITLE
Unity 2018.2

### ISSUE THREAD

**Issue by ddutchie** [JoshLmao/Spotify4Unity#3]
Hello There. 

The assetstore description says that it should be compatible with 2018.2, but there is only a version for 2018.3 is it possible to get a package for 2018.2?

Thanks!

**Comment by JoshLmao** [comment]
Sorry about that. Didn't realise that you can only use the package on the same version or above than the one I published it on. 

I've submitted an update, should be done within 24 hours (I hope) 😁
