### ISSUE TITLE
Implement implicit grant so that we don't have to authorize every 60 minutes?

### ISSUE THREAD

**Issue by yosun** [JoshLmao/Spotify4Unity#31]
**Feature Description:**
Insert your description here

**Additional context**
If possible, add some context like how this feature can help what you're making

**Comment by JoshLmao** [comment]
Spotify recently implemented a new auth method called [Authorization Code Flow with Proof Key for Code Exchange (PKCE)](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow-with-proof-key-for-code-exchange-pkce) which allows users to auth once then we, as devs, can refresh that token whenever we like. I recently implemented this on another project of mine, [Genify](https://github.com/JoshLmao/Genify) and have thought about coming back to this project to add it and fix all the other problems

**Comment by LeviVisser** [comment]
Are you still planning on updating this project?
I am currently looking into a spotify integration for my upcomming iOS and Android app. 
Eventough I followed all iOS steps exactly, I still get the INVALID_CLIENT: Invalid redirect URI on authentication.

**Comment by JoshLmao** [comment]
Hi,

Sorry for the delay. The package is updated to v2.0 where it contains PKCE auth which allows for single auth from the user. Try it out since it's a complete rewrite, and it will fix the ``` INVALID_CLIENT: Invalid redirect URI on authentication.``` issue :)
