### ISSUE TITLE
Load a pre-determined playlist?

### ISSUE THREAD

**Issue by CrashCanHero** [JoshLmao/Spotify4Unity#34]
I'm working on a game where I want the music to come from a specific playlist I've already created, I can't find much in the wiki about loading a specific playlist so I was just wondering is I can even do that?

**Comment by JoshLmao** [comment]
Hi,

Apologies for the late reply. I suggest you update to v2.0. Then, you'll be able to simple do the following code for this to work.

```
SpotifyClient client = SpotifyService.Instance.GetSpotifyClient();
if (client != null)
{
    PlayerResumePlaybackRequest request = new PlayerResumePlaybackRequest()
    {
        ContextUri = fullPlaylist.Uri,
    };
    client.Player.ResumePlayback(request);
}
```
