### ISSUE TITLE
Unity editor freezing on play. 

### ISSUE THREAD

**Issue by Mattilak** [JoshLmao/Spotify4Unity#39]
Hi Josh, just wanted to start by saying I absolutely love this plugin :) 

I created an application in unity and used the example player to display the current track info. It was working perfectly until this morning when suddenly every time I played it in both the editor and the built version they crash. I tried disabling the SpotifyService script and my application still runs fine until I attempt to connect to Spotify and it freezes. 

If you could provide some insight into why this is happening and/or how I could fix this issue would be fantastic. 

Thanks in advance!

**Comment by JoshLmao** [comment]
Hi,

Can I just check, which version of S4U are you using? It sounds like you are using the one from the asset store, v1.5 or below? If so, I've recently rewrote the whole thing so I do suggest you use v2, [found here](https://github.com/JoshLmao/Spotify4Unity/releases/tag/v2.0) which *isn't* live on the asset store yet.

Is there any info or logs you could provide with the problem? I haven't heard of a similar problem before. It could be down to a number of things as the old version (v1.5 and below) had a multitude of problems, which was my main reason for a rewrite.

**Comment by Mattilak** [comment]
Thank you for the reply. I was using v1.5 from the asset store, I downloaded v2 from the link you provided and everything is working perfectly. Thank you!

**Comment by JoshLmao** [comment]
No problem. I'm working on updating the asset store one but having a few problems. Hope to have it done asap. Any other problems, feel free to open a new issue 😊
