### ISSUE TITLE
Correct Parenting of UI Elements

### ISSUE THREAD

**Issue by ddutchie** [JoshLmao/Spotify4Unity#4]
I had some issues with World Space Canvas. You need to Parent the Instantiated prefab ui element at the same time as creating it.

EG: AcrossListBase.cs Lines 53-56

`                GameObject instantiatedPrefab = Instantiate(m_prefab);
                instantiatedPrefab.transform.SetParent(m_resizeCanvas);
                instantiatedPrefab.transform.localRotation = Quaternion.identity;
                instantiatedPrefab.transform.localScale = Vector3.one;`

or can be. 
`
GameObject instantiatedPrefab2 = Instantiate(m_prefab,Vector3.zero, Quaternion.identity, m_resizeCanvas);`

**Comment by JoshLmao** [comment]
Yeah, nice catch. Fixed that and will be in the next update. 

Quick note. The prefabs I created are meant for Screen Space however you're perfectly fine to use them for World Space. However you need to make sure the child prefab is scaled correctly since I've just discovered that 😊
