### ISSUE TITLE
Token Saver Should not save to C:\

### ISSUE THREAD

**Issue by ddutchie** [JoshLmao/Spotify4Unity#5]
In rare cases there will be no access rights to C:\ to save the JSON. 

Please make this Application.persistentDataPath by default.

**Comment by ddutchie** [comment]
I just added this to TokenSaver.cs

   ` private static string FilePathCorrected = Application.persistentDataPath + "/SpotifyTokens.json";`

Then referenced FilePathCorrected Everywhere

**Comment by JoshLmao** [comment]
By default, TokenSaver does save to Application.persistenDataPath

(TokenSaver.cs Line 17)
` private static string FilePath { get { return !string.IsNullOrEmpty(FileDirectory) ? Path.Combine(FileDirectory, FileName) : Path.Combine(BackupFileDirectory, FileName); } }
`

That will return the directory that you want or the default one which is Application.persistantDataPath + "/SpotifyTokens.json". The "FileDirectory" property is set through SpotifyService as the "AuthTokenBaseDirectory" property so as long as you're not setting that to anywhere yourself, it will use it.

**Comment by ddutchie** [comment]
For some reason even if blank it was trying to save to C:\

**Comment by JoshLmao** [comment]
Alright, this one was weird. Turns out using Path.Combine on a directory and a file name with a / at the start doesn't combine it correctly. This is fixed now
