### ISSUE TITLE
Unable to Authenticate in a Built Version

### ISSUE THREAD

**Issue by Eyliess** [JoshLmao/Spotify4Unity#6]
Using Unity 2018.3.9f1
When I export the Project to Windows, it does attempt to authenticate and even opens the browser window with the message "OK - This window can be closed now", but it doesn't authenticate and ends up timing out.

That being said, really enjoying the plugin so far and it does work on the editor, I hope I'm not missing something obvious here.

**Comment by JoshLmao** [comment]
Hi, i'm happy you like it! And turns out, the solution to this is my fault (because you need to manually set this). Can you make sure the "API Compatibility Level" in "Player Settings" is set to ".NET 4.x" and try again?

**Comment by Eyliess** [comment]
Awesome, that did the trick!
Thanks for the fast response and please keep working on this plugin - it's genuinely really cool.
