### ISSUE TITLE
ExamplePlayerController not working

### ISSUE THREAD

**Issue by bennibayer** [JoshLmao/Spotify4Unity#7]
Hi, 
nice plugin. Got it to work in unity 2019.1, so that i can connect to my spotify account in Editor and Android App.
I changed it a bit, so that i simply use the OnApplicationFocus() method in Unity to catch the intent instead of using the native android plugin as a jar.

Everything works so far, connection, getting profile informations, devices, playlist, current track and all images. Even the search works.

But i have problems with the ExamplePlayerController. The "passive" ones are ok (updating current position, current track and even playback or pause when i change it in the sportify app etc). 
But i don't get the "active" interactions to work. Like e.g. play/pause, changing volume, set looping, set shuffling or going to next/previous song.

Is it because I'm using a Free spotify account? 
Or is maybe anything wrong with the authentication, but then i should not see any profile specific information, right? 
Or is there maybe a problem with the internal UploadDataAsync<T>() method in the SpotifyWebAPI or with the REST call for play/pause or similar?

I would be glad about any help.

**Comment by JoshLmao** [comment]
It's related to the fact you're using a free Spotify account. If you check out the Spotify Web API docs, they say "if the user making the request is non-premium, a 403 FORBIDDEN response code will be returned" ([Source](https://developer.spotify.com/documentation/web-api/reference/player/skip-users-playback-to-next-track/#response-format))

I have put on the Asset Store page that functionality is limited for users who aren't premium. However, there is a "IsPremium" property on the Spotify Service which allows you to check if the current user is Premium. So just because you're using a free account, someone else might not be

Also, I'm interested in what you said about using the OnApplicationFocus method and catching the intent. I'm not very experienced on Android dev so if it's possible to not have people create the custom JAR, I'd love to implement it

**Comment by bennibayer** [comment]
Thank you for your response. 
Ok that's sad, but I understand it's not your fault. It's just the limitation of the free-account.
Sure, another user could have a premium account, but i hoped to create my app, that even spotify free-users can use it ;-)

But i found out, that there is also an url to a 30 seconds preview mp3. So i guess i can at least let free-users hear that short sound.

To the OnApplicationFocus() method.

In the AndroidManifest you need just this section inside your activity, like you described:
 ```
  <intent-filter>
        <data android:scheme="yourscheme" />
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
   </intent-filter>
```



And then you can use simply this class, which i adapted a bit. You can completely remove the .jar from your assets in this case. The code is not optimized yet, just a first approach. Feel free to ask if you have questions about it (or if you know how to improve).



  ```
  using System;
    using System.Collections;
    using System.Collections.Generic;
    using UnityEngine;
    using Spotify4Unity;
    using SpotifyAPI.Web.Enums;
    using System.Reflection;
    using System.Text.RegularExpressions;



    public class MyAdaptedAndroidSpotifyService : AndroidSpotifyService {
    
        bool getAuthorization = false;
        
        void OnApplicationFocus(bool focusStatus){
            if(focusStatus){
                if(getAuthorization){
                    Debug.Log("UNITY OnApplicationFocus() ... get Authorization");

                    AndroidJavaClass UnityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer"); 
                    AndroidJavaObject currentActivity = UnityPlayer.GetStatic<AndroidJavaObject>("currentActivity");

                    string arguments = null;

                    #if UNITY_EDITOR
                    //--> you have to adapt this line each hour. Just enter the string which you get in android logcat, when logging in on your android device
                    arguments = "yourscheme://oauth/callback/spotify/#access_token=BQAgVxYbqbYiP-XhSZP4QLOLBVQDKP7PPX5e1GZPJVrXQ09OY8duqLhZi_UaGSuplJQyilr9fo21JTYEZ04_e1c25WBqiXedlOsf7EGGBYgwQ8cEcQoE4mS_YgEMmeM1LUuGjJ0VSqX7WoAmxp8TX2TRM5TLw7GvchxddAYoXbPtbj20kqCkN2KDtdsRPA0MpyXg5etgGnnUaZosvCRSIi_pnw9J3AFp33D7ah8Y21QOKVoYj68PZGjiegj4-nQUC58RoJhpuESqtg_8e1NSGhbH-oX2hwFL1Ydpgw&token_type=Bearer&expires_in=3600";
                    
                    #elif UNITY_ANDROID
                    AndroidJavaObject intent = currentActivity.Call<AndroidJavaObject>("getIntent");
                    arguments = intent.Call<string> ("getDataString");
                    
                    #endif
                    
                    if(arguments != null){
                        Debug.Log("arguments: " + arguments);

                        Uri uri = new Uri(arguments);
                        if (uri != null && uri.ToString().StartsWith(Scheme)) {				
                            string accessToken = uri.Fragment;						
                            if(accessToken != null){							
                                OnRecievedAndroidAuth(accessToken);								
                                getAuthorization = false; //reset to avoid calling this always in editor, when loosing focus
                            }
                        }
                    }				
                }
            }
        }

        public override void Connect() {
            
            if (string.IsNullOrEmpty(this.ClientId)) {
                //Analysis.Log("Missing ClientId in Android Service", Analysis.LogLevel.Vital);
                return;
            }
            if (this.IsConnecting) {
                return;
            }
        
            this.MyBeginImplicitAuth(this.ClientId, this.RedirectUrl);   

        }

        
        private void MyBeginImplicitAuth(string clientId, string redirectUrl) {       

            string text = "token";
            string text2 = Uri.EscapeDataString(redirectUrl);
            string escapedScopes = this.MyGetEscapedScopes();
            string text3 = "https://accounts.spotify.com/authorize";
            string concattedString = string.Concat(new string[]
            {
                text3,
                "?client_id=",
                clientId,
                "&response_type=",
                text,
                "&redirect_uri=",
                text2,
                "&scope=",
                escapedScopes
            });
            
            getAuthorization = true;

            Application.OpenURL(concattedString);
        }


        private string MyGetEscapedScopes(){
        string[] array = (Scope.PlaylistModifyPublic | Scope.PlaylistModifyPrivate | Scope.PlaylistReadPrivate | Scope.Streaming | Scope.UserReadPrivate | Scope.UserReadEmail | Scope.UserLibraryRead | Scope.UserLibraryModify | Scope.UserFollowModify | Scope.UserFollowRead | Scope.UserReadBirthdate | Scope.UserTopRead | Scope.PlaylistReadCollaborative | Scope.UserReadRecentlyPlayed | Scope.UserReadPlaybackState | Scope.UserModifyPlaybackState | Scope.UserReadCurrentlyPlaying).ToString().Split(new char[]
        {
            ','
        });
        string text = "";
        for (int i = 0; i < array.Length; i++)
        {
            string[] value = Regex.Split(array[i].Replace(" ", ""), "(?<!^)(?=[A-Z])");
            text += string.Join("-", value);
            if (i < array.Length)
            {
                text += " ";
            }
        }
        return Uri.EscapeDataString(text.ToLower());
    }
```



The manual adaption in the #if UNITY_EDITOR is just necessary, because i only found out, how to reliably get the authorization token on my android device. It did not work from Unity Editor opening the browser and returning, so i decided to use just a hard-coded key during development. Maybe there is a better approach.

**Comment by JoshLmao** [comment]
Oooh, code samples! (Thank you!)

After seeing this method, I feel like it's A LOT easier than the old method. If you don't mind, I'd love to integrate the below into the current AndroidSpotifyService to make it a lot easier for everybody. The rest is the same as the current AndroidSpotifyService

```
AndroidJavaClass UnityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer"); 
AndroidJavaObject currentActivity = UnityPlayer.GetStatic<AndroidJavaObject>("currentActivity");

AndroidJavaObject intent = currentActivity.Call<AndroidJavaObject>("getIntent");
string arguments = intent.Call<string> ("getDataString");
```

I'm going to work on the support for free users in the next update because it's possible to support adverts and displaying them in the mini player. However, I'm gone all next month so I won't be able to do that until I'm back.

**Comment by bennibayer** [comment]
Sure, feel free to use it :-)

Yes i just attached the whole class, because i was not sure anymore, what exactly i did change. 

Just some tips:
- I guess  the main part is the OnApplicationFocus() method. 
- But also ensure, that you remove the ConfigureJar() call in Connect(). 
- Also ensure, that you only call it when any flag is set (like I did with the "getAuthorization" bool ). Else it is in editor always called when you click outside of the game window and back again.
- Maybe you should make the "arguments" string somehow accessible from the inspector, because it has to be updated every 60 minutes currently


Looking forward to the next update.

**Comment by bennibayer** [comment]
Short addition:
Tested it with a premium account now, and it works.
